// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/intrusion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IntrusionDetectionServiceClient is the client API for IntrusionDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntrusionDetectionServiceClient interface {
	// StreamLogs enables bi-directional streaming of log data
	// Client streams LogRequest, server responds with LogResponse
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (IntrusionDetectionService_StreamLogsClient, error)
}

type intrusionDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntrusionDetectionServiceClient(cc grpc.ClientConnInterface) IntrusionDetectionServiceClient {
	return &intrusionDetectionServiceClient{cc}
}

func (c *intrusionDetectionServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (IntrusionDetectionService_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IntrusionDetectionService_ServiceDesc.Streams[0], "/intrusion.IntrusionDetectionService/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &intrusionDetectionServiceStreamLogsClient{stream}
	return x, nil
}

type IntrusionDetectionService_StreamLogsClient interface {
	Send(*LogRequest) error
	Recv() (*LogResponse, error)
	grpc.ClientStream
}

type intrusionDetectionServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *intrusionDetectionServiceStreamLogsClient) Send(m *LogRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *intrusionDetectionServiceStreamLogsClient) Recv() (*LogResponse, error) {
	m := new(LogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntrusionDetectionServiceServer is the server API for IntrusionDetectionService service.
// All implementations must embed UnimplementedIntrusionDetectionServiceServer
// for forward compatibility
type IntrusionDetectionServiceServer interface {
	// StreamLogs enables bi-directional streaming of log data
	// Client streams LogRequest, server responds with LogResponse
	StreamLogs(IntrusionDetectionService_StreamLogsServer) error
	mustEmbedUnimplementedIntrusionDetectionServiceServer()
}

// UnimplementedIntrusionDetectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntrusionDetectionServiceServer struct {
}

func (UnimplementedIntrusionDetectionServiceServer) StreamLogs(IntrusionDetectionService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedIntrusionDetectionServiceServer) mustEmbedUnimplementedIntrusionDetectionServiceServer() {
}

// UnsafeIntrusionDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntrusionDetectionServiceServer will
// result in compilation errors.
type UnsafeIntrusionDetectionServiceServer interface {
	mustEmbedUnimplementedIntrusionDetectionServiceServer()
}

func RegisterIntrusionDetectionServiceServer(s grpc.ServiceRegistrar, srv IntrusionDetectionServiceServer) {
	s.RegisterService(&IntrusionDetectionService_ServiceDesc, srv)
}

func _IntrusionDetectionService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntrusionDetectionServiceServer).StreamLogs(&intrusionDetectionServiceStreamLogsServer{stream})
}

type IntrusionDetectionService_StreamLogsServer interface {
	Send(*LogResponse) error
	Recv() (*LogRequest, error)
	grpc.ServerStream
}

type intrusionDetectionServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *intrusionDetectionServiceStreamLogsServer) Send(m *LogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *intrusionDetectionServiceStreamLogsServer) Recv() (*LogRequest, error) {
	m := new(LogRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntrusionDetectionService_ServiceDesc is the grpc.ServiceDesc for IntrusionDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntrusionDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intrusion.IntrusionDetectionService",
	HandlerType: (*IntrusionDetectionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _IntrusionDetectionService_StreamLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/intrusion.proto",
}
